name: deploy

on:
  # Trigger the workflow on push to main branch and tutorial path
  push:
    branches:
      - main
    paths:
      - tutorial/**

# This job installs dependencies, build the jupyter notebook, and pushes it to `render`, a new `branch`
jobs:
  build:
    name: Setup
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up conda and dependencies
        uses: mamba-org/provision-with-micromamba@v14
        with:
          environment-file: .binder/environment.yml
          environment-name: clivar
          extra-specs: |
            python=3.10
          channels: conda-forge
          cache-env: true
      # Build the book
      - name: Build the book
        run: |
          jupyter-book build tutorial
      # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tutorial/_build/html
